### ISSUE TITLE
Support delay when mirroring stories flagged as sensitive 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/pivotaltrackermirror#11]
Some stories may contain sensitive content,  such as those tracking work on CVE. 

In such case, we might not want to ease discoverability of these stories into well indexed GH issue mirrors, because this would make it easier for bad guys to find information about known CVEs that have not yet associated fix available for the community.

A set of these sensitive stories identified by a set of labels, may require special handling such as delaying the reporting until a combination of:
   * a fixed elapsed time (e.g. a number of days)
   * a given story state (such as "delivered")
   * a label set on the story (such as "cve-fix-cf-released")

**Comment by gberche-orange** [comment]
A reasonable 1st step is to skip mirroring of stories with labels matching an hardcoded regexp such as "(cve)|(sec)"

**Comment by ArthurHlt** [comment]
Step one added with commit: 8dc737b

User can set a `story_filters` env var wich contains a list of text.
this list will be use to filter story for not being mirrored if it contains one member of the list in its title.

By default, we filter CVE.
Example to filter from multiple values:
```bash
$ export story_filters=CVE,other text 1, other text 2 #....
```
