### ISSUE TITLE
Some accepted stories are still mirrored as open GH issues

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/pivotaltrackermirror#13]
See https://github.com/cf-trackermirror-bot/buildpacks-tracker-mirror/issues?q=is%3Aopen+is%3Aissue+label%3Aaccepted whereas they should be closed

**Comment by ArthurHlt** [comment]
fixed on commit: 55bc9c8

Origin:
When a member of a pivotal tracker project open an accepted story (e.g: to edit it) which was created before we mirror this story is mark as edited and edit date is updated. This imply that this story will be mirrored now and should be created on github.
But github api doesn't permit to set the state of a story during creation which cannot be marked as closed.
