### ISSUE TITLE
Document API endpoints

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/pivotaltrackermirror#19]
See [controllers](https://github.com/orange-cloudfoundry/pivotaltrackermirror/tree/32ee4606067a29152cfe474d5ab3b77f52488e40/src/main/java/com/orange/clara/pivotaltrackermirror/controllers)

**Comment by ArthurHlt** [comment]
From commit efbd207 this is now documented.
We can find the endpoint in the readme, to go on it directly go to https://github.com/orange-cloudfoundry/pivotaltrackermirror/blob/master/src/docs/asciidoc/generated/api.adoc
