### ISSUE TITLE
Duplicates comment mirrors

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/pivotaltrackermirror#25]
Sometimes mirroring duplicates comments.

For instance, with https://github.com/cf-trackermirror-bot/buildpacks-tracker-mirror/issues/219, some comments are duplicated (**3 times**: Jacques Chester commented on Aug 25, 2016, 2.54 PM UTC)

**Comment by gberche-orange** [comment]
Thanks @o-orand for spotting this and reporting.

Seems to reproduce quite frequently, from [list of issues sorted by nb of comments](
https://github.com/cf-trackermirror-bot/buildpacks-tracker-mirror/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc) I spotted:
* https://github.com/cf-trackermirror-bot/buildpacks-tracker-mirror/issues/127 which has 13 duplicates for ``Jacques Chester commented on Aug 16, 2016, 8.59 PM UTC:``
* https://github.com/cf-trackermirror-bot/buildpacks-tracker-mirror/issues/22 has 13 duplicates for ``James Wen commented on Aug 17, 2016, 4.23 PM UTC:``

**Comment by ArthurHlt** [comment]
fixed on https://github.com/orange-cloudfoundry/pivotaltrackermirror/commit/325448fb882454207ccc60b3bffb90f74746125e
